name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:     # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 🔹 Updated from v3 to v4
        with:
          name: snake-gif
          path: dist/snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
